
CFLAGS=-g -Wall
SRCS=	Makefile sljtest.c getopt.c replgetopt.h
	
sljtest: getopt.o sljtest.o
	${CC} ${LDLAGS} -o $@ -lm getopt.o sljtest.o

sljtest.o: replgetopt.h sljtest.c
	${CC} ${CFLAGS}   -c -o sljtest.o sljtest.c

clean:
	rm -r -f *.o sljtest
