
CFLAGS=-g -Wall
SRCS=	Makefile sjtest.c getopt.c replgetopt.h
	
sjtest: getopt.o sjtest.o
	${CC} ${LDLAGS} -o $@ -lm getopt.o sjtest.o

sjtest.o: replgetopt.h sjtest.c
	${CC} ${CFLAGS}   -c -o sjtest.o sjtest.c

clean:
	rm -r -f *.o sjtest
